name: publish
on:
  push:
    branches:
      - master
jobs:
  publish-m3u-editor-docker-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ” authenticating with docker hub"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "ğŸ›  building and pushing docker image"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sparkison/m3u-editor:latest
